### PR TITLE
Add a minimal example

### PR DESCRIPTION
**Pull request by orhun**
Hey! 🐻

I wanted to use `tachyonfx` for one of my TUI projects and needed a minimal guide to get started.

This PR simply adds a more minimal example which just renders a couple of effects :)
Let me know if you like this & feel free to tweak it as you like!

Thanks for the awesome library 🚀

### CODE REVIEW

**Comment by junkdog** [comment]
Hi :wave:  Good thinking! It's always good to have an example without all the clutter.

**Comment by orhun** [comment]
Btw I worked on this on a stream if you are interested: https://www.youtube.com/watch?v=pCI_rZp3DLQ

**Comment by junkdog** [comment]
> Btw I worked on this on a stream if you are interested: https://www.youtube.com/watch?v=pCI_rZp3DLQ

This sort of thing is super helpful/insightful! I'm sorry you had to struggle with getting the effect to render :sweat_smile:  It could have been averted with some basic documentation... I'll probably just inline your example in the README.

I'm enjoying the stream. Good stuff! About halfway through, will cont tomorrow.

**Comment by orhun** [comment]
Thank you! Great to hear, I [recently](https://blog.orhun.dev/livestreaming/) started streaming and it is a lot of fun :)

>  It could have been averted with some basic documentation... I'll probably just inline your example in the README.

Yup, perfect!

**Comment by orhun** [comment]
Btw do you like the functionality in the example? I also had another idea where a function such as `get_random_effect` will return a random effect so that we'll see something different on each run. But I'm not sure if it is too much for a _minimal_ example + don't know the most straightforward way to implement it.

**Comment by junkdog** [comment]
> Btw do you like the functionality in the example? 

I do. It shows the basic setup example and can be expanded upon by the user.

> `get_random_effect`

I think it's fine without as `basic-example` and `fx-chart` already do something similar.

One alternative is to combine the glitch into one effect - using a sleep() before glitch, but it shows less of the API (no need to check is_running() or track duration):

```rust
fn main() -> io::Result<()> {
    let mut terminal = ratatui::init();

    // You can construct effects using the builder pattern.
    let mut glitch: Effect = Glitch::builder()
        .rng(SimpleRng::default())
        .action_ms(200..400)
        .action_start_delay_ms(0..1)
        .cell_glitch_ratio(1.0)
        .build()
        .into_effect();

    // Or you can use the provided effect combinators.
    let mut effect = fx::sequence(&[
        // first we "sweep in" the text from the left, before reversing the effect
        fx::ping_pong(fx::sweep_in(
            FxDirection::LeftToRight,
            10,
            0,
            Color::DarkGray,
            EffectTimer::from_ms(2000, Interpolation::QuadIn),
        )),
        // then we coalesce the text back to its original state
        // (note that EffectTimers can be constructed from a tuple of duration and interpolation)
        fx::coalesce((800, Interpolation::SineOut)),
        sleep(7200),
        glitch
    ]);

    loop {
        // Render the glitch effect after 10 seconds.
        terminal.draw(|f| ui(f, &mut effect))?;
        if event::poll(StdDuration::from_millis(33))? { // ~30FPS
            if let Event::Key(_) = event::read()? {
                break;
            }
        }
    }
    ratatui::restore();
    Ok(())
}
````

We should probably change the polling to  ~30hz; makes the animation smoother.

**Pull request merged**
